POST http://localhost:8080/api/auth/login
Content-Type: application/json


# happy path
{
  "email": "codelearner@example.com",
  "password": "password123"
}

###

# unhappy path

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "codelearner@example.com",
"password": "password12344556"
}


###
# get current user by unique token - expect 200

GET http://localhost:8080/api/auth/me
Authorization: Bearer {{authToken}}


###
# get current user by missing unique token - expect 401

GET http://localhost:8080/api/auth/me

### Log in and save JWT for this HTTP Client session
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "codelearner@example.com",
  "password": "password123"
}

> {% client.global.set("authToken", response.body.token); %}

### Submit a correct Java solution — expect 200 / correct: true
POST http://localhost:8080/api/exercises/1/submissions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "sourceCode": "public class Main {\n    public static void main(String[] args) {\n        int age = 25;\n        System.out.println(age);\n    }\n}"
}


### Submit a correct Java solution — expect 200 / correct: false
POST http://localhost:8080/api/exercises/1/submissions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "sourceCode": "public class Main {\n    public static void main(String[] args) {\n        int age = 22;\n        System.out.println(age);\n    }\n}"
}